# Generated by Django 3.1.1 on 2021-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='Updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Delete'),
        ),
    ]
