# Generated by Django 3.1.1 on 2021-05-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logstore', '0003_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
