# Generated by Django 3.1.1 on 2021-05-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logstore', '0004_auto_20210506_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
