# Generated by Django 3.1.1 on 2021-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logstore', '0006_log_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='sender_name',
            field=models.CharField(default='', max_length=50, verbose_name='SenderName'),
        ),
    ]
