# Generated by Django 3.1.1 on 2021-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Log Name')),
                ('category', models.CharField(max_length=20, verbose_name='Log Type')),
                ('limit', models.CharField(max_length=20, verbose_name='Log 权限')),
                ('introduce', models.CharField(max_length=20, verbose_name='Log introduction')),
                ('content', models.TextField(verbose_name='Log Content')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('Updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
