# Generated by Django 3.1.1 on 2021-05-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='publisher',
            new_name='editor',
        ),
    ]
